[General]
background=backgrounds/mountains.svg
backgroundFill=#1d2021
backgroundFillMode=aspect
blur=false
recursiveBlurLoops=0
recursiveBlurRadius=0

ScreenWidth=1920
ScreenHeight=1080

Font=JetBrains Mono Nerd Font
FontSize=12

basicTextColor=#ebdbb2
passwordTextColor=#ebdbb2
passwordInputBackground=#3c3836
passwordInputRadius=8
passwordInputBorderWidth=1
passwordInputBorderColor=#504945
passwordInputCursorVisible=true
passwordCursorColor=#ebdbb2
passwordFontSize=28
passwordInputWidth=0.3
passwordMask=true
passwordCharacter=•

showUsersByDefault=true
showSessionsByDefault=true
usersFontSize=24
sessionsFontSize=18
