-- ==================================================
-- Chris King - Hyprland v1
-- Arch Linux / Laptop / Catppuccin Base
-- ==================================================

------------------
---- MONITORS ----
------------------

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- ================================================
-- COLOURS
-- Defaults — overridden by colors.lua (generated by wallust) once it has run
-- ================================================

local defaultColors = { accent = "rgb(c4956a)", border_inactive = "rgb(252525)" }
local ok, colors = pcall(require, "colors")
if not ok then
    colors = defaultColors
end

-- ================================================
-- VARIABLES
-- ================================================

local mainMod     = "SUPER"
local terminal     = "kitty"
local fileManager  = "thunar"
local menu         = "fuzzel"
local browser      = "zen-browser"

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/scripts/wallpaper.sh")
    hl.exec_cmd("~/.config/hypr/scripts/waybar-launch.sh")
    hl.exec_cmd("~/.config/hypr/scripts/workspace-watch.py")
    hl.exec_cmd("swaync")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("bash -c 'while true; do ~/.config/hypr/scripts/battery-check.sh; sleep 120; done'")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("~/.config/hypr/scripts/syncthing-notify.sh")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("GDK_BACKEND", "wayland,x11")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in  = 6,
        gaps_out = 12,

        border_size = 2,

        col = {
            active_border   = colors.accent,
            inactive_border = colors.border_inactive,
        },

        resize_on_border = true,
        allow_tearing    = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 8,
            render_power = 3,
            color        = "rgba(0a0906ee)",
        },

        blur = {
            enabled  = true,
            size     = 5,
            passes   = 2,
            vibrancy = 0.15,
        },
    },

    animations = {
        enabled = true,
    },
})

-- bezier(name, x0, y0, x1, y1) -> control points (x0,y0) and (x1,y1) between (0,0) and (1,1)
hl.curve("smooth", { type = "bezier", points = { { 0.22, 0.9 }, { 0.3, 1.0 } } })
hl.curve("soft",   { type = "bezier", points = { { 0.25, 0.8 }, { 0.25, 1.0 } } })
hl.curve("quick",  { type = "bezier", points = { { 0.15, 0.0 }, { 0.1, 1.0 } } })

hl.animation({ leaf = "windows",        enabled = true, speed = 6, bezier = "smooth" })
hl.animation({ leaf = "windowsIn",      enabled = true, speed = 6, bezier = "smooth", style = "popin 85%" })
hl.animation({ leaf = "windowsOut",     enabled = true, speed = 5, bezier = "soft",   style = "popin 85%" })
hl.animation({ leaf = "border",         enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade",           enabled = true, speed = 6, bezier = "soft" })
hl.animation({ leaf = "workspaces",     enabled = true, speed = 6, bezier = "smooth" })
hl.animation({ leaf = "layers",         enabled = true, speed = 5, bezier = "smooth" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 6, bezier = "smooth", style = "slidevert" })

-- ================================================
-- LAYOUTS
-- ================================================

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

-- ================================================
-- INPUT
-- ================================================

hl.config({
    input = {
        kb_layout    = "gb",
        follow_mouse = 1,
        sensitivity  = 0,

        touchpad = {
            natural_scroll        = true,
            tap_to_click          = true,
            drag_lock             = false,
            clickfinger_behavior  = true,
            scroll_factor         = 1.0,
        },
    },
})

-- ================================================
-- KEYBINDS
-- ================================================

-- Apps
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal), { desc = "Open terminal" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager), { desc = "Open file manager" })
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu), { desc = "Open app launcher" })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("hyprlock"), { desc = "Lock screen" })
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("swaync-client -t"), { desc = "Toggle notification center" })
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("~/.config/hypr/scripts/nightmode.sh"), { desc = "Toggle night mode (blue light filter)" })
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("~/.config/hypr/scripts/nvim-workspace.sh"), { desc = "Open Neovim workspace" })
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("~/.config/hypr/scripts/scratchpad.sh"), { desc = "Toggle scratchpad terminal" })
hl.bind(mainMod .. " + SHIFT + slash", hl.dsp.exec_cmd("~/.config/hypr/scripts/keybind-search.sh"), { desc = "Search keybindings by what they do and run them" })
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("~/.config/hypr/scripts/obsidian-scratch.sh"), { desc = "Open Obsidian scratch note" })
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd("~/.config/hypr/scripts/sleep-inhibit-toggle.sh"), { desc = "Toggle automatic sleep on/off" })

-- Windows
hl.bind(mainMod .. " + Q", hl.dsp.window.close(), { desc = "Close active window" })
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.kill(), { desc = "Force close unresponsive window" })
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized" }), { desc = "Toggle fullscreen" })
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd("~/.config/hypr/scripts/float-and-center.sh"), { desc = "Toggle floating and center window" })
hl.bind(mainMod .. " + SHIFT + Space", hl.dsp.window.center(), { desc = "Center floating window" })
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exit(), { desc = "Exit Hyprland session (log out)" })
hl.bind(mainMod .. " + H", hl.dsp.window.resize({ x = -80, y = 0, relative = true }), { desc = "Shrink window width" })
hl.bind(mainMod .. " + L", hl.dsp.window.resize({ x = 80, y = 0, relative = true }), { desc = "Grow window width" })
hl.bind(mainMod .. " + K", hl.dsp.window.resize({ x = 0, y = -80, relative = true }), { desc = "Shrink window height" })
hl.bind(mainMod .. " + J", hl.dsp.window.resize({ x = 0, y = 80, relative = true }), { desc = "Grow window height" })

-- Focus movement between tiled windows
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.focus({ direction = "left" }),  { desc = "Move focus left" })
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.focus({ direction = "down" }),  { desc = "Move focus down" })
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.focus({ direction = "up" }),    { desc = "Move focus up" })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.focus({ direction = "right" }), { desc = "Move focus right" })

-- Workspace cycling
hl.bind(mainMod .. " + right", hl.dsp.focus({ workspace = "e+1" }), { desc = "Switch to next workspace" })
hl.bind(mainMod .. " + left",  hl.dsp.focus({ workspace = "e-1" }), { desc = "Switch to previous workspace" })
hl.bind(mainMod .. " + TAB",   hl.dsp.focus({ workspace = "previous" }), { desc = "Switch to last used workspace" })

-- Numbered workspaces / move windows to workspaces
for i = 1, 5 do
    hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = i }),       { desc = "Switch to workspace " .. i })
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }), { desc = "Move window to workspace " .. i })
end

-- Mouse workspace switching
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { desc = "Scroll to next workspace" })
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), { desc = "Scroll to previous workspace" })

-- Mouse move/resize
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true, desc = "Drag window with mouse" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, desc = "Resize window with mouse" })

-- Clipboard
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | fuzzel --dmenu | cliphist decode | wl-copy"), { desc = "Open clipboard history" })

-- Window switcher
hl.bind("ALT + Tab", hl.dsp.window.cycle_next(), { desc = "Switch windows (alt-tab)" })
hl.bind("ALT + SHIFT + Tab", hl.dsp.window.cycle_next({ previous = true }), { desc = "Switch windows backwards" })

-- Screenshot
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy && notify-send "Screenshot" "Copied to clipboard"]]), { desc = "Screenshot region to clipboard" })
hl.bind(mainMod .. " + CTRL + S", hl.dsp.exec_cmd([[grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png && notify-send "Screenshot" "Saved to Pictures/Screenshots"]]), { desc = "Screenshot region to file" })
hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy"), { desc = "Screenshot full screen to clipboard" })
-- hl.bind("SHIFT + Print", hl.dsp.exec_cmd([[grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png]]))
hl.bind(mainMod .. " + ALT + S", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | swappy -f -]]), { desc = "Screenshot region and annotate" })

-- Color picker — copies hex to clipboard
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd([[hyprpicker -a && notify-send "Colour Picker" "Colour copied to clipboard"]]), { desc = "Pick color from screen" })

-- Btop system monitor
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("~/.config/hypr/scripts/btop-toggle.sh"), { desc = "Toggle floating system monitor" })

-- ================================================
-- WINDOW RULES
-- ================================================

hl.window_rule({ name = "center-floating", match = { float = true }, center = true })

-- Scratchpad terminal
hl.window_rule({ name = "scratchpad-float",     match = { class = "^(scratchpad)$" }, float = true })
hl.window_rule({ name = "scratchpad-workspace", match = { class = "^(scratchpad)$" }, workspace = "special:scratchpad silent" })
hl.window_rule({ name = "scratchpad-border",    match = { class = "^(scratchpad)$" }, border_size = 0 })

-- Network passphrase prompt
hl.window_rule({ name = "network-connect-float",  match = { title = "^(network-connect)$" }, float = true })
hl.window_rule({ name = "network-connect-size",   match = { title = "^(network-connect)$" }, size = "500 200" })
hl.window_rule({ name = "network-connect-center", match = { title = "^(network-connect)$" }, center = true })

-- Calendar popup — float below the clock, fixed size, no animation
hl.window_rule({ name = "calendar-float", match = { class = "^(calendar)$" }, float = true })
hl.window_rule({ name = "calendar-size",  match = { class = "^(calendar)$" }, size = "440 320" })
hl.window_rule({ name = "calendar-move",  match = { class = "^(calendar)$" }, move = "740 52" })

-- Btop floating monitor
hl.window_rule({ name = "btop-float-float",  match = { class = "^(btop-float)$" }, float = true })
hl.window_rule({ name = "btop-float-center", match = { class = "^(btop-float)$" }, center = true })

-- ================================================
-- MEDIA KEYS
-- ================================================

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { locked = true, repeating = true, desc = "Raise volume" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { locked = true, repeating = true, desc = "Lower volume" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true, repeating = true, desc = "Mute/unmute volume" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"), { locked = true, repeating = true, desc = "Mute/unmute microphone" })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness raise"), { locked = true, repeating = true, desc = "Increase screen brightness" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower"), { locked = true, repeating = true, desc = "Decrease screen brightness" })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, desc = "Next track" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true, desc = "Previous track" })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, desc = "Play/pause media" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, desc = "Play/pause media" })

-- ================================================
-- MISC
-- ================================================

hl.config({
    misc = {
        disable_hyprland_logo   = true,
        force_default_wallpaper = 0,
    },
})
