background            {{ background }}
foreground            #d0d0d0
cursor                {{ color13 }}
cursor_text_color     {{ background }}
selection_background  #505050
selection_foreground  #d0d0d0

color0   {{ color0 }}
color1   {{ color9 }}
color2   {{ color10 }}
color3   {{ color11 }}
color4   {{ color12 }}
color5   {{ color13 }}
color6   {{ color14 }}
color7   #9a9a9a
color8   #505050
color9   {{ color9 }}
color10  {{ color10 }}
color11  {{ color11 }}
color12  {{ color12 }}
color13  {{ color13 }}
color14  {{ color14 }}
color15  #d0d0d0
